### ISSUE TITLE
MUSICPLAYER example

### ISSUE THREAD

**Issue by tmrobert8** [NEEOInc/neeo-sdk-examples#10]
Can't seem to get the music player example running correctly.  I've started it up, added it to NEEO but the directories are always empty (doesn't show the hardcoded ones in the example) - doesn't seem like the directory stuff is setup correctly?

Secondly - is there any chance you can make the directory stuff optional (if no directories specified, simply bring up the song details popup and leave it that way?).  Reason being, many systems stream music and won't have a playlist or any type of queue to manage.  Seems like this control is specifically geared towards sonos (which if it is, should be a special type then - not something generic like musicplayer)..

**Comment by neophob** [comment]
Which version of the Brain do you use?

the directory stuff is optional - depending on your driver. the idea of this player is to have a complete example. you can remove the directories if you want.

**Comment by tmrobert8** [comment]
Firmware 51.4

Ah – I went on the following comment in the code (which made it sound like a required item).  Since the directory stuff wasn’t working – I couldn’t play with it to see if it’s required or not:
```
* The player widget requires a lot of different components:
 * - Switches
 *   - MUTE (including MUTE_SENSOR)
 *   - PLAYING (including PLAYING_SENSOR)
 *   - REPEAT (including REPEAT_SENSOR)
 *   - SHUFFLE (including SHUFFLE_SENSOR)
 * - Sliders
 *   - VOLUME (including VOLUME_SENSOR)
 * - Sensors (read only)
 *   - COVER_ART_SENSOR
 *   - TITLE_SENSOR
 *   - DESCRIPTION_SENSOR
 * - Directories
 *   - A root directory
 *   - A queue directory
```

**Comment by neophob** [comment]
More hints:
- you ran `npm install` on the examples to include the latest `neeo-sdk` repo?
- You re-added the device from the latest sdk examples directory?

**Comment by tmrobert8** [comment]
Yes to both (the SDK is definitely next)

**Comment by tmrobert8** [comment]
BTW - the remote doesn't give this but the APP does:  "There was something fishy going on: ERROR_DIRECTORY_BROWSER_NO_DIRECTORY"

**Comment by neophob** [comment]
I rechecked, currently directories must be enabled. I created https://github.com/NEEOInc/neeo-sdk/issues/113 for that.
For now you just can return an empty directory

**Comment by neophob** [comment]
You're right, there's an error - but will be solved with the next firmware/sdk release.

thanks for reporting!

**Comment by neophob** [comment]
new example provided
