### ISSUE TITLE
PR/Branch Name

### ISSUE THREAD

**Issue by tmrobert8** [NEEOInc/neeo-sdk-examples#3]
Is there any format you want for branch names (and/or the PR name itself) when doing a pull request?  If you take a page from openHAB - the PR (and branch) would be named "XXX-YYY" where XXX is the issue ID and YYY would be some descriptive name.  So if I did a pull request based on this issue for an example named 'stuff' - the branch and PR would be named "3-Stuff"

**Comment by neophob** [comment]
hi @tmrobert8 

currently a name is enough for a pr.

thanks
