### ISSUE TITLE
Typo ?

### ISSUE THREAD

**Issue by rhuss** [NEEOInc/neeo-sdk-examples#8]
While reading through https://planet.neeo.com/t/k9tnlp and following examples I stumpled upon:

https://github.com/NEEOInc/neeo-sdk-examples/blob/fb9186d12199732b416cb18e2488765bd6da80d8/device/simpleDevice/index.js#L42

Although not tried, it heavily smells after a typo either here or in the SDK. Shouldn't it be called `addButtonHandler` ?

**Comment by neophob** [comment]
Indeed, this typo is also present on the sdk itself. Thanks, will be fixed in the next release!
