### ISSUE TITLE
Running and using of example code not possible

### ISSUE THREAD

**Issue by carp3-noctem** [NEEOInc/neeo-sdk-examples#9]
When using the Readme to run the Examples, this is not working as described, also there is no "short" way to start the Listview NOR it is exported as a device to the CLI, or did i oversee something here?

**Comment by neophob** [comment]
`npm install && npm start` works fine for me.

The Listview example can be added when you're searching for the `File Browser SDK Example` device. then you need to create a shortcut.

Can you explain what does not work as expected and add some logs if possible?

**Comment by neophob** [comment]
I've update the @next branch with the latest example, feel free to reopen is this still does not work as expected
